// Starter content for the Danish learning app: built-in decks and cards.
// These are "system" decks/cards (ownerId = null) shared by every user.
// Seeding is idempotent (see seed.js), so this file can grow over time and a
// re-deploy will only add what's new.

export const DECKS = [
  // =========================================================================
  // VOCAB
  // =========================================================================
  {
    name: "Food & Drink",
    category: "vocab",
    description: "Everyday words for eating and drinking (mad og drikke).",
    cards: [
      { danishText: "brød", englishText: "bread", exampleSentence: "Jeg spiser brød til morgenmad." },
      { danishText: "smør", englishText: "butter", exampleSentence: "Vil du have smør på dit brød?" },
      { danishText: "ost", englishText: "cheese", exampleSentence: "Dansk ost er meget populær." },
      { danishText: "æg", englishText: "egg / eggs", exampleSentence: "Jeg vil gerne have to æg." },
      { danishText: "mælk", englishText: "milk", exampleSentence: "Der er ikke mere mælk." },
      { danishText: "kaffe", englishText: "coffee", exampleSentence: "Jeg drikker kaffe hver morgen." },
      { danishText: "te", englishText: "tea", exampleSentence: "Vil du have en kop te?" },
      { danishText: "vand", englishText: "water", exampleSentence: "Må jeg få et glas vand?" },
      { danishText: "øl", englishText: "beer", exampleSentence: "En øl, tak." },
      { danishText: "frugt", englishText: "fruit", exampleSentence: "Frugt er sundt." },
      { danishText: "æble", englishText: "apple", exampleSentence: "Hun spiser et æble." },
      { danishText: "grøntsager", englishText: "vegetables", exampleSentence: "Vi køber friske grøntsager." },
      { danishText: "kød", englishText: "meat", exampleSentence: "Jeg spiser ikke kød." },
      { danishText: "fisk", englishText: "fish", exampleSentence: "Fisk smager godt med citron." },
      { danishText: "sukker", englishText: "sugar", exampleSentence: "Jeg tager ikke sukker i kaffen." },
      { danishText: "morgenmad", englishText: "breakfast", exampleSentence: "Morgenmad er dagens vigtigste måltid." },
    ],
  },
  {
    name: "Travel",
    category: "vocab",
    description: "Getting around and going on holiday (rejse).",
    cards: [
      { danishText: "at rejse", englishText: "to travel", exampleSentence: "Jeg elsker at rejse." },
      { danishText: "tog", englishText: "train", exampleSentence: "Toget kører klokken otte." },
      { danishText: "bus", englishText: "bus", exampleSentence: "Bussen er forsinket." },
      { danishText: "fly", englishText: "airplane", exampleSentence: "Flyet lander om en time." },
      { danishText: "billet", englishText: "ticket", exampleSentence: "Jeg har købt en billet." },
      { danishText: "bagage", englishText: "luggage", exampleSentence: "Min bagage er tung." },
      { danishText: "lufthavn", englishText: "airport", exampleSentence: "Vi mødes i lufthavnen." },
      { danishText: "hotel", englishText: "hotel", exampleSentence: "Hotellet ligger i centrum." },
      { danishText: "kort", englishText: "map", exampleSentence: "Har du et kort over byen?" },
      { danishText: "vej", englishText: "road / way", exampleSentence: "Hvilken vej skal vi gå?" },
      { danishText: "station", englishText: "station", exampleSentence: "Stationen er tæt på." },
      { danishText: "pas", englishText: "passport", exampleSentence: "Husk dit pas." },
      { danishText: "ferie", englishText: "holiday / vacation", exampleSentence: "Vi skal på ferie i Spanien." },
      { danishText: "by", englishText: "city / town", exampleSentence: "København er en smuk by." },
      { danishText: "udland", englishText: "abroad", exampleSentence: "Hun bor i udlandet." },
    ],
  },
  {
    name: "Work",
    category: "vocab",
    description: "The workplace and office life (arbejde).",
    cards: [
      { danishText: "at arbejde", englishText: "to work", exampleSentence: "Jeg arbejder på et kontor." },
      { danishText: "job", englishText: "job", exampleSentence: "Hun har fået et nyt job." },
      { danishText: "kontor", englishText: "office", exampleSentence: "Kontoret er lukket i dag." },
      { danishText: "møde", englishText: "meeting", exampleSentence: "Vi har et møde klokken ti." },
      { danishText: "chef", englishText: "boss", exampleSentence: "Min chef er meget flink." },
      { danishText: "kollega", englishText: "colleague", exampleSentence: "Han er en god kollega." },
      { danishText: "computer", englishText: "computer", exampleSentence: "Min computer er gået i stykker." },
      { danishText: "løn", englishText: "salary / pay", exampleSentence: "Jeg får løn sidst på måneden." },
      { danishText: "opgave", englishText: "task", exampleSentence: "Jeg har en vigtig opgave." },
      { danishText: "projekt", englishText: "project", exampleSentence: "Projektet er næsten færdigt." },
      { danishText: "telefon", englishText: "telephone", exampleSentence: "Telefonen ringer." },
      { danishText: "e-mail", englishText: "email", exampleSentence: "Jeg sender dig en e-mail." },
    ],
  },
  {
    name: "Home & Family",
    category: "vocab",
    description: "People and places at home (hjem og familie).",
    cards: [
      { danishText: "hus", englishText: "house", exampleSentence: "De bor i et stort hus." },
      { danishText: "lejlighed", englishText: "apartment / flat", exampleSentence: "Min lejlighed er lille, men hyggelig." },
      { danishText: "familie", englishText: "family", exampleSentence: "Jeg elsker min familie." },
      { danishText: "mor", englishText: "mother", exampleSentence: "Min mor hedder Anne." },
      { danishText: "far", englishText: "father", exampleSentence: "Min far arbejder som læge." },
      { danishText: "barn", englishText: "child", exampleSentence: "De har ét barn." },
      { danishText: "børn", englishText: "children", exampleSentence: "Børnene leger i haven." },
      { danishText: "bror", englishText: "brother", exampleSentence: "Jeg har en storebror." },
      { danishText: "søster", englishText: "sister", exampleSentence: "Min søster er ældre end mig." },
      { danishText: "ven", englishText: "friend", exampleSentence: "Han er min bedste ven." },
      { danishText: "værelse", englishText: "room", exampleSentence: "Mit værelse er ryddeligt." },
      { danishText: "køkken", englishText: "kitchen", exampleSentence: "Vi spiser i køkkenet." },
    ],
  },
  {
    name: "Numbers & Time",
    category: "vocab",
    description: "Talking about days, weeks and the clock (tal og tid).",
    cards: [
      { danishText: "tid", englishText: "time", exampleSentence: "Jeg har ikke tid i dag." },
      { danishText: "time", englishText: "hour", exampleSentence: "Jeg venter en time." },
      { danishText: "dag", englishText: "day", exampleSentence: "Hav en god dag!" },
      { danishText: "uge", englishText: "week", exampleSentence: "Vi ses i næste uge." },
      { danishText: "måned", englishText: "month", exampleSentence: "Der er tolv måneder i et år." },
      { danishText: "år", englishText: "year", exampleSentence: "Godt nytår!" },
      { danishText: "i dag", englishText: "today", exampleSentence: "I dag er det mandag." },
      { danishText: "i morgen", englishText: "tomorrow", exampleSentence: "Vi ses i morgen." },
      { danishText: "i går", englishText: "yesterday", exampleSentence: "I går regnede det." },
      { danishText: "nu", englishText: "now", exampleSentence: "Jeg kommer nu." },
      { danishText: "klokken", englishText: "o'clock", exampleSentence: "Klokken er tre." },
      { danishText: "morgen", englishText: "morning", exampleSentence: "Om morgenen drikker jeg kaffe." },
      { danishText: "aften", englishText: "evening", exampleSentence: "Vi spiser aftensmad klokken seks." },
      { danishText: "weekend", englishText: "weekend", exampleSentence: "God weekend!" },
    ],
  },

  // =========================================================================
  // GRAMMAR
  // For grammar cards the Danish side is a worked example, the English side is
  // its translation, and the note (example sentence) states the rule.
  // =========================================================================
  {
    name: "Word Order",
    category: "grammar",
    description: "Danish sentence structure and the V2 rule (ordstilling).",
    cards: [
      { danishText: "Jeg spiser et æble.", englishText: "I eat an apple.", exampleSentence: "Rule: Basic main-clause order is Subject–Verb–Object (SVO)." },
      { danishText: "I dag spiser jeg et æble.", englishText: "Today I eat an apple.", exampleSentence: "Rule (V2): if something else starts the sentence, the verb stays 2nd and the subject moves after it." },
      { danishText: "Han drikker ikke kaffe.", englishText: "He does not drink coffee.", exampleSentence: "Rule: in main clauses 'ikke' comes after the finite verb." },
      { danishText: "Hvad laver du?", englishText: "What are you doing?", exampleSentence: "Rule: in wh-questions the verb comes straight after the question word, before the subject." },
      { danishText: "Drikker du te?", englishText: "Do you drink tea?", exampleSentence: "Rule: yes/no questions start with the verb, then the subject." },
      { danishText: "Om sommeren rejser vi til Danmark.", englishText: "In the summer we travel to Denmark.", exampleSentence: "Rule: a fronted adverbial triggers inversion — verb 2nd, subject 3rd." },
      { danishText: "Jeg ved, at han kommer.", englishText: "I know that he is coming.", exampleSentence: "Rule: subordinate clauses (after 'at') keep subject–verb order." },
      { danishText: "Hun sagde, at hun ikke kunne komme.", englishText: "She said that she couldn't come.", exampleSentence: "Rule: in subordinate clauses 'ikke' comes BEFORE the finite verb." },
      { danishText: "Jeg står op klokken syv.", englishText: "I get up at seven o'clock.", exampleSentence: "Rule: with particle verbs (stå op) the particle follows the subject." },
      { danishText: "Kan du hjælpe mig?", englishText: "Can you help me?", exampleSentence: "Rule: a modal verb comes first in yes/no questions; the main verb stays in the infinitive." },
    ],
  },
  {
    name: "Verb Conjugation",
    category: "grammar",
    description: "Present, past and perfect tenses (verbernes bøjning).",
    cards: [
      { danishText: "jeg taler, du taler, han taler", englishText: "I / you / he speak(s)", exampleSentence: "Rule: present tense is the same for all persons — just add -r to the stem." },
      { danishText: "at spise → jeg spiser", englishText: "to eat → I eat", exampleSentence: "Rule: regular verbs form the present by adding -r to the infinitive." },
      { danishText: "jeg talte dansk", englishText: "I spoke Danish", exampleSentence: "Rule: regular past tense adds -ede or -te to the stem (tale → talte)." },
      { danishText: "jeg har talt", englishText: "I have spoken", exampleSentence: "Rule: perfect = har/er + past participle (talt)." },
      { danishText: "at være → jeg er", englishText: "to be → I am", exampleSentence: "Irregular: er (present), var (past), været (perfect)." },
      { danishText: "at have → jeg har", englishText: "to have → I have", exampleSentence: "Irregular: har (present), havde (past), haft (perfect)." },
      { danishText: "at gå → jeg gik", englishText: "to go / walk → I went", exampleSentence: "Irregular: går, gik, gået." },
      { danishText: "at komme → jeg kom", englishText: "to come → I came", exampleSentence: "Irregular: kommer, kom, kommet. Perfect uses 'er': jeg er kommet." },
      { danishText: "at kunne → jeg kan", englishText: "to be able to → I can", exampleSentence: "Modal verb: kan, kunne, kunnet." },
      { danishText: "at ville → jeg vil", englishText: "to want / will → I want", exampleSentence: "Modal verb: vil, ville, villet." },
    ],
  },
  {
    name: "en / et Articles",
    category: "grammar",
    description: "Common vs. neuter gender and definite forms.",
    cards: [
      { danishText: "en bil", englishText: "a car", exampleSentence: "Common gender (n-word). About 75% of nouns are 'en' words." },
      { danishText: "et hus", englishText: "a house", exampleSentence: "Neuter gender (t-word). About 25% of nouns are 'et' words." },
      { danishText: "en mand", englishText: "a man", exampleSentence: "'en' word (common gender)." },
      { danishText: "et barn", englishText: "a child", exampleSentence: "'et' word (neuter gender)." },
      { danishText: "bilen", englishText: "the car", exampleSentence: "Rule: the definite article is a suffix — en bil → bilen (add -en)." },
      { danishText: "huset", englishText: "the house", exampleSentence: "Rule: definite of 'et' words adds -et — et hus → huset." },
      { danishText: "en kvinde", englishText: "a woman", exampleSentence: "'en' word; definite: kvinden." },
      { danishText: "et æble", englishText: "an apple", exampleSentence: "'et' word; definite: æblet." },
      { danishText: "en dag", englishText: "a day", exampleSentence: "'en' word; definite: dagen." },
      { danishText: "et år", englishText: "a year", exampleSentence: "'et' word; definite: året." },
    ],
  },
  {
    name: "Plurals",
    category: "grammar",
    description: "Forming the plural, definite and irregular (flertal).",
    cards: [
      { danishText: "en bil → to biler", englishText: "one car → two cars", exampleSentence: "Rule: the most common plural adds -er." },
      { danishText: "et hus → to huse", englishText: "one house → two houses", exampleSentence: "Rule: many nouns add -e in the plural." },
      { danishText: "et æble → to æbler", englishText: "one apple → two apples", exampleSentence: "Rule: nouns ending in -e usually add -r." },
      { danishText: "en bog → to bøger", englishText: "one book → two books", exampleSentence: "Irregular: vowel change o → ø, plus -er." },
      { danishText: "et barn → to børn", englishText: "one child → two children", exampleSentence: "Irregular plural: barn → børn." },
      { danishText: "en mand → to mænd", englishText: "one man → two men", exampleSentence: "Irregular: vowel change a → æ." },
      { danishText: "en ven → to venner", englishText: "one friend → two friends", exampleSentence: "Rule: double the final consonant, then add -er." },
      { danishText: "biler → bilerne", englishText: "cars → the cars", exampleSentence: "Rule: the definite plural adds -ne (or -ene)." },
      { danishText: "huse → husene", englishText: "houses → the houses", exampleSentence: "Rule: definite plural adds -ne." },
      { danishText: "et år → to år", englishText: "one year → two years", exampleSentence: "Rule: some nouns are unchanged in the plural." },
    ],
  },

  // =========================================================================
  // LISTENING (short phrases — great with the audio button)
  // =========================================================================
  {
    name: "Everyday Phrases",
    category: "listening",
    description: "Short spoken phrases for daily conversation.",
    cards: [
      { danishText: "Hej, hvordan går det?", englishText: "Hi, how are you?", exampleSentence: "A friendly greeting." },
      { danishText: "Det går godt, tak.", englishText: "I'm doing well, thanks.", exampleSentence: "A common reply to 'hvordan går det?'." },
      { danishText: "Hvad hedder du?", englishText: "What's your name?", exampleSentence: "Literally: 'What are you called?'" },
      { danishText: "Jeg hedder Anna.", englishText: "My name is Anna.", exampleSentence: "'hedde' = to be called." },
      { danishText: "Hvor kommer du fra?", englishText: "Where are you from?", exampleSentence: "Ask about someone's origin." },
      { danishText: "Jeg forstår ikke.", englishText: "I don't understand.", exampleSentence: "Very useful when learning!" },
      { danishText: "Kan du gentage det?", englishText: "Can you repeat that?", exampleSentence: "Ask someone to say it again." },
      { danishText: "Taler du engelsk?", englishText: "Do you speak English?", exampleSentence: "A lifesaver phrase." },
      { danishText: "Undskyld, hvor er toilettet?", englishText: "Excuse me, where is the toilet?", exampleSentence: "'undskyld' = excuse me / sorry." },
      { danishText: "Hvad koster det?", englishText: "How much does it cost?", exampleSentence: "Ask for a price." },
      { danishText: "Jeg vil gerne have en kop kaffe.", englishText: "I would like a cup of coffee.", exampleSentence: "'jeg vil gerne have' = I would like." },
      { danishText: "Tak for hjælpen.", englishText: "Thanks for the help.", exampleSentence: "Polite thanks." },
      { danishText: "Vi ses i morgen.", englishText: "See you tomorrow.", exampleSentence: "A casual goodbye." },
      { danishText: "Ha' en god dag!", englishText: "Have a good day!", exampleSentence: "'ha'' is short for 'have'." },
      { danishText: "Hvad er klokken?", englishText: "What time is it?", exampleSentence: "Literally: 'What is the clock?'" },
    ],
  },
  {
    name: "At the Café & Shop",
    category: "listening",
    description: "Phrases you'll hear when ordering and shopping.",
    cards: [
      { danishText: "Hvad kan jeg hjælpe med?", englishText: "What can I help you with?", exampleSentence: "A shop assistant's greeting." },
      { danishText: "Jeg kigger bare, tak.", englishText: "I'm just looking, thanks.", exampleSentence: "Polite way to browse." },
      { danishText: "Må jeg bede om regningen?", englishText: "May I have the bill, please?", exampleSentence: "'må jeg bede om' = may I ask for." },
      { danishText: "Kan jeg betale med kort?", englishText: "Can I pay by card?", exampleSentence: "Denmark is largely cashless." },
      { danishText: "Har I noget uden gluten?", englishText: "Do you have anything gluten-free?", exampleSentence: "'uden' = without." },
      { danishText: "En kop kaffe og et stykke kage, tak.", englishText: "A cup of coffee and a piece of cake, please.", exampleSentence: "'et stykke' = a piece." },
      { danishText: "Vil du have en pose?", englishText: "Would you like a bag?", exampleSentence: "Often asked at the checkout." },
      { danishText: "Det er på huset.", englishText: "It's on the house.", exampleSentence: "Meaning it's free." },
      { danishText: "Kan jeg få en kvittering?", englishText: "Can I get a receipt?", exampleSentence: "'kvittering' = receipt." },
      { danishText: "Vi har åbent til klokken seks.", englishText: "We're open until six o'clock.", exampleSentence: "'åbent' = open (opening hours)." },
      { danishText: "Har I et ledigt bord?", englishText: "Do you have a free table?", exampleSentence: "'ledig' = available / free." },
      { danishText: "Nyd måltidet!", englishText: "Enjoy your meal!", exampleSentence: "Said before eating." },
    ],
  },
];
