// Starter content for the Danish learning app: built-in decks and cards.
// These are "system" decks/cards (ownerId = null) shared by every user.
// Seeding is idempotent (see seed.js), so this file can grow over time and a
// re-deploy will only add what's new.

export const DECKS = [
  // =========================================================================
  // VOCAB
  // =========================================================================
  {
    name: "Food & Drink",
    category: "vocab",
    language: "da",
    description: "Everyday words for eating and drinking (mad og drikke).",
    cards: [
      { targetText: "brød", nativeText: "bread", exampleSentence: "Jeg spiser brød til morgenmad." },
      { targetText: "smør", nativeText: "butter", exampleSentence: "Vil du have smør på dit brød?" },
      { targetText: "ost", nativeText: "cheese", exampleSentence: "Dansk ost er meget populær." },
      { targetText: "æg", nativeText: "egg / eggs", exampleSentence: "Jeg vil gerne have to æg." },
      { targetText: "mælk", nativeText: "milk", exampleSentence: "Der er ikke mere mælk." },
      { targetText: "kaffe", nativeText: "coffee", exampleSentence: "Jeg drikker kaffe hver morgen." },
      { targetText: "te", nativeText: "tea", exampleSentence: "Vil du have en kop te?" },
      { targetText: "vand", nativeText: "water", exampleSentence: "Må jeg få et glas vand?" },
      { targetText: "øl", nativeText: "beer", exampleSentence: "En øl, tak." },
      { targetText: "frugt", nativeText: "fruit", exampleSentence: "Frugt er sundt." },
      { targetText: "æble", nativeText: "apple", exampleSentence: "Hun spiser et æble." },
      { targetText: "grøntsager", nativeText: "vegetables", exampleSentence: "Vi køber friske grøntsager." },
      { targetText: "kød", nativeText: "meat", exampleSentence: "Jeg spiser ikke kød." },
      { targetText: "fisk", nativeText: "fish", exampleSentence: "Fisk smager godt med citron." },
      { targetText: "sukker", nativeText: "sugar", exampleSentence: "Jeg tager ikke sukker i kaffen." },
      { targetText: "morgenmad", nativeText: "breakfast", exampleSentence: "Morgenmad er dagens vigtigste måltid." },
    ],
  },
  {
    name: "Travel",
    category: "vocab",
    language: "da",
    description: "Getting around and going on holiday (rejse).",
    cards: [
      { targetText: "at rejse", nativeText: "to travel", exampleSentence: "Jeg elsker at rejse." },
      { targetText: "tog", nativeText: "train", exampleSentence: "Toget kører klokken otte." },
      { targetText: "bus", nativeText: "bus", exampleSentence: "Bussen er forsinket." },
      { targetText: "fly", nativeText: "airplane", exampleSentence: "Flyet lander om en time." },
      { targetText: "billet", nativeText: "ticket", exampleSentence: "Jeg har købt en billet." },
      { targetText: "bagage", nativeText: "luggage", exampleSentence: "Min bagage er tung." },
      { targetText: "lufthavn", nativeText: "airport", exampleSentence: "Vi mødes i lufthavnen." },
      { targetText: "hotel", nativeText: "hotel", exampleSentence: "Hotellet ligger i centrum." },
      { targetText: "kort", nativeText: "map", exampleSentence: "Har du et kort over byen?" },
      { targetText: "vej", nativeText: "road / way", exampleSentence: "Hvilken vej skal vi gå?" },
      { targetText: "station", nativeText: "station", exampleSentence: "Stationen er tæt på." },
      { targetText: "pas", nativeText: "passport", exampleSentence: "Husk dit pas." },
      { targetText: "ferie", nativeText: "holiday / vacation", exampleSentence: "Vi skal på ferie i Spanien." },
      { targetText: "by", nativeText: "city / town", exampleSentence: "København er en smuk by." },
      { targetText: "udland", nativeText: "abroad", exampleSentence: "Hun bor i udlandet." },
    ],
  },
  {
    name: "Work",
    category: "vocab",
    language: "da",
    description: "The workplace and office life (arbejde).",
    cards: [
      { targetText: "at arbejde", nativeText: "to work", exampleSentence: "Jeg arbejder på et kontor." },
      { targetText: "job", nativeText: "job", exampleSentence: "Hun har fået et nyt job." },
      { targetText: "kontor", nativeText: "office", exampleSentence: "Kontoret er lukket i dag." },
      { targetText: "møde", nativeText: "meeting", exampleSentence: "Vi har et møde klokken ti." },
      { targetText: "chef", nativeText: "boss", exampleSentence: "Min chef er meget flink." },
      { targetText: "kollega", nativeText: "colleague", exampleSentence: "Han er en god kollega." },
      { targetText: "computer", nativeText: "computer", exampleSentence: "Min computer er gået i stykker." },
      { targetText: "løn", nativeText: "salary / pay", exampleSentence: "Jeg får løn sidst på måneden." },
      { targetText: "opgave", nativeText: "task", exampleSentence: "Jeg har en vigtig opgave." },
      { targetText: "projekt", nativeText: "project", exampleSentence: "Projektet er næsten færdigt." },
      { targetText: "telefon", nativeText: "telephone", exampleSentence: "Telefonen ringer." },
      { targetText: "e-mail", nativeText: "email", exampleSentence: "Jeg sender dig en e-mail." },
    ],
  },
  {
    name: "Home & Family",
    category: "vocab",
    language: "da",
    description: "People and places at home (hjem og familie).",
    cards: [
      { targetText: "hus", nativeText: "house", exampleSentence: "De bor i et stort hus." },
      { targetText: "lejlighed", nativeText: "apartment / flat", exampleSentence: "Min lejlighed er lille, men hyggelig." },
      { targetText: "familie", nativeText: "family", exampleSentence: "Jeg elsker min familie." },
      { targetText: "mor", nativeText: "mother", exampleSentence: "Min mor hedder Anne." },
      { targetText: "far", nativeText: "father", exampleSentence: "Min far arbejder som læge." },
      { targetText: "barn", nativeText: "child", exampleSentence: "De har ét barn." },
      { targetText: "børn", nativeText: "children", exampleSentence: "Børnene leger i haven." },
      { targetText: "bror", nativeText: "brother", exampleSentence: "Jeg har en storebror." },
      { targetText: "søster", nativeText: "sister", exampleSentence: "Min søster er ældre end mig." },
      { targetText: "ven", nativeText: "friend", exampleSentence: "Han er min bedste ven." },
      { targetText: "værelse", nativeText: "room", exampleSentence: "Mit værelse er ryddeligt." },
      { targetText: "køkken", nativeText: "kitchen", exampleSentence: "Vi spiser i køkkenet." },
    ],
  },
  {
    name: "Numbers & Time",
    category: "vocab",
    language: "da",
    description: "Talking about days, weeks and the clock (tal og tid).",
    cards: [
      { targetText: "tid", nativeText: "time", exampleSentence: "Jeg har ikke tid i dag." },
      { targetText: "time", nativeText: "hour", exampleSentence: "Jeg venter en time." },
      { targetText: "dag", nativeText: "day", exampleSentence: "Hav en god dag!" },
      { targetText: "uge", nativeText: "week", exampleSentence: "Vi ses i næste uge." },
      { targetText: "måned", nativeText: "month", exampleSentence: "Der er tolv måneder i et år." },
      { targetText: "år", nativeText: "year", exampleSentence: "Godt nytår!" },
      { targetText: "i dag", nativeText: "today", exampleSentence: "I dag er det mandag." },
      { targetText: "i morgen", nativeText: "tomorrow", exampleSentence: "Vi ses i morgen." },
      { targetText: "i går", nativeText: "yesterday", exampleSentence: "I går regnede det." },
      { targetText: "nu", nativeText: "now", exampleSentence: "Jeg kommer nu." },
      { targetText: "klokken", nativeText: "o'clock", exampleSentence: "Klokken er tre." },
      { targetText: "morgen", nativeText: "morning", exampleSentence: "Om morgenen drikker jeg kaffe." },
      { targetText: "aften", nativeText: "evening", exampleSentence: "Vi spiser aftensmad klokken seks." },
      { targetText: "weekend", nativeText: "weekend", exampleSentence: "God weekend!" },
    ],
  },

  {
    name: "Colors & Numbers",
    category: "vocab",
    language: "da",
    description: "Beginner: essential colors and counting 1–12 (farver og tal).",
    cards: [
      { targetText: "rød", nativeText: "red", exampleSentence: "Bilen er rød." },
      { targetText: "blå", nativeText: "blue", exampleSentence: "Himlen er blå i dag." },
      { targetText: "grøn", nativeText: "green", exampleSentence: "Græsset er grønt." },
      { targetText: "gul", nativeText: "yellow", exampleSentence: "Solen er gul." },
      { targetText: "sort", nativeText: "black", exampleSentence: "Katten er sort." },
      { targetText: "hvid", nativeText: "white", exampleSentence: "Sneen er hvid." },
      { targetText: "brun", nativeText: "brown", exampleSentence: "Bordet er brunt." },
      { targetText: "grå", nativeText: "grey / gray", exampleSentence: "Himlen er grå om vinteren." },
      { targetText: "en, et", nativeText: "one", exampleSentence: "Jeg har en bror og et barn." },
      { targetText: "to", nativeText: "two", exampleSentence: "Jeg har to søskende." },
      { targetText: "tre", nativeText: "three", exampleSentence: "Klokken er tre." },
      { targetText: "fire", nativeText: "four", exampleSentence: "Der er fire årstider." },
      { targetText: "fem", nativeText: "five", exampleSentence: "Jeg starter klokken fem." },
      { targetText: "seks", nativeText: "six", exampleSentence: "Butikken lukker klokken seks." },
      { targetText: "syv", nativeText: "seven", exampleSentence: "Der er syv dage i en uge." },
      { targetText: "otte", nativeText: "eight", exampleSentence: "Toget kører klokken otte." },
      { targetText: "ni", nativeText: "nine", exampleSentence: "Vi mødes klokken ni." },
      { targetText: "ti", nativeText: "ten", exampleSentence: "Det koster ti kroner." },
      { targetText: "elleve", nativeText: "eleven", exampleSentence: "Filmen starter klokken elleve." },
      { targetText: "tolv", nativeText: "twelve", exampleSentence: "Der er tolv måneder i et år." },
    ],
  },
  {
    name: "Idioms & Expressions",
    category: "vocab",
    language: "da",
    description: "Advanced: figurative phrases that don't translate literally (talemåder).",
    cards: [
      { targetText: "der er ugler i mosen", nativeText: "something's fishy / suspicious", exampleSentence: "Literally: 'there are owls in the bog'." },
      { targetText: "at tage benene på nakken", nativeText: "to run away quickly", exampleSentence: "Literally: 'to put your legs on your neck'." },
      { targetText: "at koste skjorten", nativeText: "to cost a fortune", exampleSentence: "Literally: 'to cost the shirt'." },
      { targetText: "at slå to fluer med ét smæk", nativeText: "to kill two birds with one stone", exampleSentence: "Literally: 'to hit two flies with one smack'." },
      { targetText: "at være ude på dybt vand", nativeText: "to be out of one's depth", exampleSentence: "Literally: 'to be out in deep water'." },
      { targetText: "at gå agurk", nativeText: "to go crazy / berserk", exampleSentence: "Literally: 'to go cucumber' — modern slang." },
      { targetText: "at få kolde fødder", nativeText: "to get cold feet", exampleSentence: "Same image as the English idiom." },
      { targetText: "det blæser en halv pelikan", nativeText: "it's extremely windy", exampleSentence: "Literally: 'it's blowing half a pelican'." },
      { targetText: "at tale rent ud af posen", nativeText: "to speak plainly / frankly", exampleSentence: "Literally: 'to talk straight out of the bag'." },
      { targetText: "at have sommerfugle i maven", nativeText: "to have butterflies in one's stomach", exampleSentence: "Same image as the English idiom." },
    ],
  },

  // =========================================================================
  // GRAMMAR
  // For grammar cards the Danish side is a worked example, the English side is
  // its translation, and the note (example sentence) states the rule.
  // =========================================================================
  {
    name: "Word Order",
    category: "grammar",
    language: "da",
    description: "Danish sentence structure and the V2 rule (ordstilling).",
    cards: [
      { targetText: "Jeg spiser et æble.", nativeText: "I eat an apple.", exampleSentence: "Rule: Basic main-clause order is Subject–Verb–Object (SVO)." },
      { targetText: "I dag spiser jeg et æble.", nativeText: "Today I eat an apple.", exampleSentence: "Rule (V2): if something else starts the sentence, the verb stays 2nd and the subject moves after it." },
      { targetText: "Han drikker ikke kaffe.", nativeText: "He does not drink coffee.", exampleSentence: "Rule: in main clauses 'ikke' comes after the finite verb." },
      { targetText: "Hvad laver du?", nativeText: "What are you doing?", exampleSentence: "Rule: in wh-questions the verb comes straight after the question word, before the subject." },
      { targetText: "Drikker du te?", nativeText: "Do you drink tea?", exampleSentence: "Rule: yes/no questions start with the verb, then the subject." },
      { targetText: "Om sommeren rejser vi til Danmark.", nativeText: "In the summer we travel to Denmark.", exampleSentence: "Rule: a fronted adverbial triggers inversion — verb 2nd, subject 3rd." },
      { targetText: "Jeg ved, at han kommer.", nativeText: "I know that he is coming.", exampleSentence: "Rule: subordinate clauses (after 'at') keep subject–verb order." },
      { targetText: "Hun sagde, at hun ikke kunne komme.", nativeText: "She said that she couldn't come.", exampleSentence: "Rule: in subordinate clauses 'ikke' comes BEFORE the finite verb." },
      { targetText: "Jeg står op klokken syv.", nativeText: "I get up at seven o'clock.", exampleSentence: "Rule: with particle verbs (stå op) the particle follows the subject." },
      { targetText: "Kan du hjælpe mig?", nativeText: "Can you help me?", exampleSentence: "Rule: a modal verb comes first in yes/no questions; the main verb stays in the infinitive." },
    ],
  },
  {
    name: "Verb Conjugation",
    category: "grammar",
    language: "da",
    description: "Present, past and perfect tenses (verbernes bøjning).",
    cards: [
      { targetText: "jeg taler, du taler, han taler", nativeText: "I / you / he speak(s)", exampleSentence: "Rule: present tense is the same for all persons — just add -r to the stem." },
      { targetText: "at spise → jeg spiser", nativeText: "to eat → I eat", exampleSentence: "Rule: regular verbs form the present by adding -r to the infinitive." },
      { targetText: "jeg talte dansk", nativeText: "I spoke Danish", exampleSentence: "Rule: regular past tense adds -ede or -te to the stem (tale → talte)." },
      { targetText: "jeg har talt", nativeText: "I have spoken", exampleSentence: "Rule: perfect = har/er + past participle (talt)." },
      { targetText: "at være → jeg er", nativeText: "to be → I am", exampleSentence: "Irregular: er (present), var (past), været (perfect)." },
      { targetText: "at have → jeg har", nativeText: "to have → I have", exampleSentence: "Irregular: har (present), havde (past), haft (perfect)." },
      { targetText: "at gå → jeg gik", nativeText: "to go / walk → I went", exampleSentence: "Irregular: går, gik, gået." },
      { targetText: "at komme → jeg kom", nativeText: "to come → I came", exampleSentence: "Irregular: kommer, kom, kommet. Perfect uses 'er': jeg er kommet." },
      { targetText: "at kunne → jeg kan", nativeText: "to be able to → I can", exampleSentence: "Modal verb: kan, kunne, kunnet." },
      { targetText: "at ville → jeg vil", nativeText: "to want / will → I want", exampleSentence: "Modal verb: vil, ville, villet." },
    ],
  },
  {
    name: "en / et Articles",
    category: "grammar",
    language: "da",
    description: "Common vs. neuter gender and definite forms.",
    cards: [
      { targetText: "en bil", nativeText: "a car", exampleSentence: "Common gender (n-word). About 75% of nouns are 'en' words." },
      { targetText: "et hus", nativeText: "a house", exampleSentence: "Neuter gender (t-word). About 25% of nouns are 'et' words." },
      { targetText: "en mand", nativeText: "a man", exampleSentence: "'en' word (common gender)." },
      { targetText: "et barn", nativeText: "a child", exampleSentence: "'et' word (neuter gender)." },
      { targetText: "bilen", nativeText: "the car", exampleSentence: "Rule: the definite article is a suffix — en bil → bilen (add -en)." },
      { targetText: "huset", nativeText: "the house", exampleSentence: "Rule: definite of 'et' words adds -et — et hus → huset." },
      { targetText: "en kvinde", nativeText: "a woman", exampleSentence: "'en' word; definite: kvinden." },
      { targetText: "et æble", nativeText: "an apple", exampleSentence: "'et' word; definite: æblet." },
      { targetText: "en dag", nativeText: "a day", exampleSentence: "'en' word; definite: dagen." },
      { targetText: "et år", nativeText: "a year", exampleSentence: "'et' word; definite: året." },
    ],
  },
  {
    name: "Plurals",
    category: "grammar",
    language: "da",
    description: "Forming the plural, definite and irregular (flertal).",
    cards: [
      { targetText: "en bil → to biler", nativeText: "one car → two cars", exampleSentence: "Rule: the most common plural adds -er." },
      { targetText: "et hus → to huse", nativeText: "one house → two houses", exampleSentence: "Rule: many nouns add -e in the plural." },
      { targetText: "et æble → to æbler", nativeText: "one apple → two apples", exampleSentence: "Rule: nouns ending in -e usually add -r." },
      { targetText: "en bog → to bøger", nativeText: "one book → two books", exampleSentence: "Irregular: vowel change o → ø, plus -er." },
      { targetText: "et barn → to børn", nativeText: "one child → two children", exampleSentence: "Irregular plural: barn → børn." },
      { targetText: "en mand → to mænd", nativeText: "one man → two men", exampleSentence: "Irregular: vowel change a → æ." },
      { targetText: "en ven → to venner", nativeText: "one friend → two friends", exampleSentence: "Rule: double the final consonant, then add -er." },
      { targetText: "biler → bilerne", nativeText: "cars → the cars", exampleSentence: "Rule: the definite plural adds -ne (or -ene)." },
      { targetText: "huse → husene", nativeText: "houses → the houses", exampleSentence: "Rule: definite plural adds -ne." },
      { targetText: "et år → to år", nativeText: "one year → two years", exampleSentence: "Rule: some nouns are unchanged in the plural." },
    ],
  },

  {
    name: "Modal Verbs & Nuance",
    category: "grammar",
    language: "da",
    description: "Intermediate: the tricky difference between skulle, burde, måtte and turde.",
    cards: [
      { targetText: "du bør læse bogen", nativeText: "you should read the book", exampleSentence: "Rule: 'burde' expresses a recommendation or moral obligation (should/ought to)." },
      { targetText: "du skal læse bogen", nativeText: "you must / are supposed to read the book", exampleSentence: "Rule: 'skulle' expresses a stronger obligation or instruction than 'burde'." },
      { targetText: "du må gerne komme ind", nativeText: "you're welcome to come in", exampleSentence: "Rule: 'må gerne' grants permission — a very common polite construction." },
      { targetText: "du må ikke ryge her", nativeText: "you must not smoke here", exampleSentence: "Warning: 'må ikke' means FORBIDDEN, not merely 'don't have to' — a classic mix-up." },
      { targetText: "du behøver ikke komme", nativeText: "you don't have to come", exampleSentence: "Contrast with 'må ikke': 'behøver ikke' removes an obligation, it doesn't forbid." },
      { targetText: "jeg tør ikke sige det", nativeText: "I dare not say it", exampleSentence: "Rule: 'turde' (to dare) expresses fear or hesitation." },
      { targetText: "jeg gider ikke", nativeText: "I can't be bothered", exampleSentence: "Colloquial modal-like verb 'gide' — very common in spoken Danish." },
      { targetText: "det kan være sandt", nativeText: "that could be true", exampleSentence: "Rule: 'kan' expresses possibility, not ability, in this context." },
      { targetText: "hun skulle have ringet", nativeText: "she should have called", exampleSentence: "Rule: 'skulle have' + past participle expresses an unfulfilled past obligation." },
      { targetText: "vi må hellere gå", nativeText: "we'd better go", exampleSentence: "Idiom: 'må hellere' = 'had better', a fixed modal expression." },
    ],
  },
  {
    name: "Passive Voice",
    category: "grammar",
    language: "da",
    description: "Advanced: the -s passive vs. the blive-passive (passiv).",
    cards: [
      { targetText: "huset bygges", nativeText: "the house is being built", exampleSentence: "Rule: the -s passive suits general, ongoing, or official statements." },
      { targetText: "huset blev bygget", nativeText: "the house was built", exampleSentence: "Rule: the blive-passive is more common in speech, especially for a single completed event." },
      { targetText: "bogen læses af mange", nativeText: "the book is read by many", exampleSentence: "Rule: the agent is introduced with 'af' (by) in either passive form." },
      { targetText: "vinduet blev åbnet", nativeText: "the window was opened", exampleSentence: "Rule: blive + past participle for a specific past action." },
      { targetText: "der bliver serveret mad klokken syv", nativeText: "food is being served at seven", exampleSentence: "Rule: 'der' + blive-passive is common for existential/impersonal statements." },
      { targetText: "det siges, at han er syg", nativeText: "it is said that he is sick", exampleSentence: "Rule: impersonal -s passive, common for hearsay or reported claims." },
      { targetText: "opgaven skal løses", nativeText: "the task must be solved", exampleSentence: "Rule: a modal verb + the -s passive infinitive (løses)." },
      { targetText: "brevet er blevet sendt", nativeText: "the letter has been sent", exampleSentence: "Rule: perfect passive = er/har blevet + past participle." },
      { targetText: "hun blev født i 1990", nativeText: "she was born in 1990", exampleSentence: "Fixed expression: 'blive født' (to be born) always uses the blive-passive." },
      { targetText: "møderne holdes om mandagen", nativeText: "the meetings are held on Mondays", exampleSentence: "Rule: the -s passive suits recurring, habitual events." },
    ],
  },

  // =========================================================================
  // LISTENING (short phrases — great with the audio button)
  // =========================================================================
  {
    name: "Everyday Phrases",
    category: "listening",
    language: "da",
    description: "Short spoken phrases for daily conversation.",
    cards: [
      { targetText: "Hej, hvordan går det?", nativeText: "Hi, how are you?", exampleSentence: "A friendly greeting." },
      { targetText: "Det går godt, tak.", nativeText: "I'm doing well, thanks.", exampleSentence: "A common reply to 'hvordan går det?'." },
      { targetText: "Hvad hedder du?", nativeText: "What's your name?", exampleSentence: "Literally: 'What are you called?'" },
      { targetText: "Jeg hedder Anna.", nativeText: "My name is Anna.", exampleSentence: "'hedde' = to be called." },
      { targetText: "Hvor kommer du fra?", nativeText: "Where are you from?", exampleSentence: "Ask about someone's origin." },
      { targetText: "Jeg forstår ikke.", nativeText: "I don't understand.", exampleSentence: "Very useful when learning!" },
      { targetText: "Kan du gentage det?", nativeText: "Can you repeat that?", exampleSentence: "Ask someone to say it again." },
      { targetText: "Taler du engelsk?", nativeText: "Do you speak English?", exampleSentence: "A lifesaver phrase." },
      { targetText: "Undskyld, hvor er toilettet?", nativeText: "Excuse me, where is the toilet?", exampleSentence: "'undskyld' = excuse me / sorry." },
      { targetText: "Hvad koster det?", nativeText: "How much does it cost?", exampleSentence: "Ask for a price." },
      { targetText: "Jeg vil gerne have en kop kaffe.", nativeText: "I would like a cup of coffee.", exampleSentence: "'jeg vil gerne have' = I would like." },
      { targetText: "Tak for hjælpen.", nativeText: "Thanks for the help.", exampleSentence: "Polite thanks." },
      { targetText: "Vi ses i morgen.", nativeText: "See you tomorrow.", exampleSentence: "A casual goodbye." },
      { targetText: "Ha' en god dag!", nativeText: "Have a good day!", exampleSentence: "'ha'' is short for 'have'." },
      { targetText: "Hvad er klokken?", nativeText: "What time is it?", exampleSentence: "Literally: 'What is the clock?'" },
    ],
  },
  {
    name: "At the Café & Shop",
    category: "listening",
    language: "da",
    description: "Phrases you'll hear when ordering and shopping.",
    cards: [
      { targetText: "Hvad kan jeg hjælpe med?", nativeText: "What can I help you with?", exampleSentence: "A shop assistant's greeting." },
      { targetText: "Jeg kigger bare, tak.", nativeText: "I'm just looking, thanks.", exampleSentence: "Polite way to browse." },
      { targetText: "Må jeg bede om regningen?", nativeText: "May I have the bill, please?", exampleSentence: "'må jeg bede om' = may I ask for." },
      { targetText: "Kan jeg betale med kort?", nativeText: "Can I pay by card?", exampleSentence: "Denmark is largely cashless." },
      { targetText: "Har I noget uden gluten?", nativeText: "Do you have anything gluten-free?", exampleSentence: "'uden' = without." },
      { targetText: "En kop kaffe og et stykke kage, tak.", nativeText: "A cup of coffee and a piece of cake, please.", exampleSentence: "'et stykke' = a piece." },
      { targetText: "Vil du have en pose?", nativeText: "Would you like a bag?", exampleSentence: "Often asked at the checkout." },
      { targetText: "Det er på huset.", nativeText: "It's on the house.", exampleSentence: "Meaning it's free." },
      { targetText: "Kan jeg få en kvittering?", nativeText: "Can I get a receipt?", exampleSentence: "'kvittering' = receipt." },
      { targetText: "Vi har åbent til klokken seks.", nativeText: "We're open until six o'clock.", exampleSentence: "'åbent' = open (opening hours)." },
      { targetText: "Har I et ledigt bord?", nativeText: "Do you have a free table?", exampleSentence: "'ledig' = available / free." },
      { targetText: "Nyd måltidet!", nativeText: "Enjoy your meal!", exampleSentence: "Said before eating." },
    ],
  },
  {
    name: "Weather & Small Talk",
    category: "listening",
    language: "da",
    description: "Intermediate: chit-chat about the weather and your day (småsnak).",
    cards: [
      { targetText: "Sikke et vejr i dag!", nativeText: "What weather today!", exampleSentence: "A common exclamation, good or bad." },
      { targetText: "Det regner katte og hunde.", nativeText: "It's raining cats and dogs.", exampleSentence: "This idiom matches English almost exactly." },
      { targetText: "Solen skinner smukt.", nativeText: "The sun is shining beautifully.", exampleSentence: "'skinne' = to shine." },
      { targetText: "Det er koldt herude.", nativeText: "It's cold out here.", exampleSentence: "'herude' = out here." },
      { targetText: "Vejrudsigten siger sne i morgen.", nativeText: "The forecast says snow tomorrow.", exampleSentence: "'vejrudsigt' = weather forecast." },
      { targetText: "Hvordan var din weekend?", nativeText: "How was your weekend?", exampleSentence: "A very common small-talk opener." },
      { targetText: "Den var ret stille, faktisk.", nativeText: "It was pretty quiet, actually.", exampleSentence: "'faktisk' = actually." },
      { targetText: "Skal vi tage en kop kaffe sammen engang?", nativeText: "Should we grab a coffee together sometime?", exampleSentence: "A casual way to suggest meeting up." },
      { targetText: "Det lyder hyggeligt.", nativeText: "That sounds cozy / nice.", exampleSentence: "'hyggeligt' — the famously untranslatable Danish word for cozy contentment." },
      { targetText: "Jeg glæder mig til weekenden.", nativeText: "I'm looking forward to the weekend.", exampleSentence: "'glæde sig til' = to look forward to." },
    ],
  },
  {
    name: "Natural Conversation & Idioms",
    category: "listening",
    language: "da",
    description: "Advanced: fast, idiomatic phrases the way Danes actually talk.",
    cards: [
      { targetText: "Jeg har ikke rigtig tid til det i øjeblikket.", nativeText: "I don't really have time for that right now.", exampleSentence: "'i øjeblikket' = at the moment." },
      { targetText: "Det kommer an på, hvad du mener.", nativeText: "It depends on what you mean.", exampleSentence: "'det kommer an på' = it depends on." },
      { targetText: "Jeg er ikke helt med på, hvad du siger.", nativeText: "I'm not quite following what you're saying.", exampleSentence: "'være med på' = to follow / be on board." },
      { targetText: "Lad os tage det derfra, det virker fint.", nativeText: "Let's go from there, that works fine.", exampleSentence: "'tage det derfra' = to take it from there." },
      { targetText: "Det er lige meget for mig.", nativeText: "It doesn't matter to me either way.", exampleSentence: "'lige meget' = doesn't matter / all the same." },
      { targetText: "Jeg skal lige tænke over det.", nativeText: "I need to think it over for a moment.", exampleSentence: "'lige' softens the sentence — very common filler in spoken Danish." },
      { targetText: "Er du med på den?", nativeText: "Are you in / on board with that?", exampleSentence: "Casual way to check someone's agreement." },
      { targetText: "Det var flot klaret!", nativeText: "That was well done!", exampleSentence: "'klare' = to manage / pull off." },
      { targetText: "Vi tager den derfra, når vi når dertil.", nativeText: "We'll cross that bridge when we get there.", exampleSentence: "'når vi når dertil' = when we get there." },
      { targetText: "Jeg er ret træt af det hele, ærlig talt.", nativeText: "I'm pretty tired of it all, honestly.", exampleSentence: "'ærlig talt' = honestly / frankly speaking." },
    ],
  },

  // =========================================================================
  // JAPANESE (starter set)
  // =========================================================================
  {
    name: "Greetings",
    category: "vocab",
    language: "ja",
    description: "Everyday greetings and basic pleasantries (あいさつ).",
    cards: [
      { targetText: "こんにちは", nativeText: "hello / good afternoon", exampleSentence: "Reading: konnichiwa" },
      { targetText: "おはようございます", nativeText: "good morning", exampleSentence: "Reading: ohayou gozaimasu" },
      { targetText: "こんばんは", nativeText: "good evening", exampleSentence: "Reading: konbanwa" },
      { targetText: "さようなら", nativeText: "goodbye", exampleSentence: "Reading: sayounara" },
      { targetText: "またね", nativeText: "see you later", exampleSentence: "Reading: mata ne — casual, for friends." },
      { targetText: "おやすみなさい", nativeText: "good night", exampleSentence: "Reading: oyasuminasai" },
      { targetText: "はじめまして", nativeText: "nice to meet you", exampleSentence: "Reading: hajimemashite — said only the first time you meet someone." },
      { targetText: "お元気ですか", nativeText: "how are you?", exampleSentence: "Reading: ogenki desu ka" },
      { targetText: "元気です", nativeText: "I'm fine", exampleSentence: "Reading: genki desu" },
      { targetText: "お久しぶりです", nativeText: "long time no see", exampleSentence: "Reading: ohisashiburi desu" },
    ],
  },
  {
    name: "Numbers",
    category: "vocab",
    language: "ja",
    description: "Counting from one to a thousand (数字).",
    cards: [
      { targetText: "一", nativeText: "one", exampleSentence: "Reading: ichi" },
      { targetText: "二", nativeText: "two", exampleSentence: "Reading: ni" },
      { targetText: "三", nativeText: "three", exampleSentence: "Reading: san" },
      { targetText: "四", nativeText: "four", exampleSentence: "Reading: yon (also shi)" },
      { targetText: "五", nativeText: "five", exampleSentence: "Reading: go" },
      { targetText: "六", nativeText: "six", exampleSentence: "Reading: roku" },
      { targetText: "七", nativeText: "seven", exampleSentence: "Reading: nana (also shichi)" },
      { targetText: "八", nativeText: "eight", exampleSentence: "Reading: hachi" },
      { targetText: "九", nativeText: "nine", exampleSentence: "Reading: kyuu (also ku)" },
      { targetText: "十", nativeText: "ten", exampleSentence: "Reading: juu" },
      { targetText: "百", nativeText: "hundred", exampleSentence: "Reading: hyaku" },
      { targetText: "千", nativeText: "thousand", exampleSentence: "Reading: sen" },
    ],
  },
  {
    name: "Food & Drink",
    category: "vocab",
    language: "ja",
    description: "Everyday words for eating and drinking (食べ物と飲み物).",
    cards: [
      { targetText: "ご飯", nativeText: "rice / a meal", exampleSentence: "Reading: gohan" },
      { targetText: "パン", nativeText: "bread", exampleSentence: "Reading: pan" },
      { targetText: "水", nativeText: "water", exampleSentence: "Reading: mizu" },
      { targetText: "お茶", nativeText: "tea", exampleSentence: "Reading: ocha" },
      { targetText: "コーヒー", nativeText: "coffee", exampleSentence: "Reading: koohii" },
      { targetText: "魚", nativeText: "fish", exampleSentence: "Reading: sakana" },
      { targetText: "肉", nativeText: "meat", exampleSentence: "Reading: niku" },
      { targetText: "野菜", nativeText: "vegetables", exampleSentence: "Reading: yasai" },
      { targetText: "果物", nativeText: "fruit", exampleSentence: "Reading: kudamono" },
      { targetText: "卵", nativeText: "egg", exampleSentence: "Reading: tamago" },
      { targetText: "牛乳", nativeText: "milk", exampleSentence: "Reading: gyuunyuu" },
      { targetText: "お寿司", nativeText: "sushi", exampleSentence: "Reading: osushi" },
    ],
  },
  {
    name: "Common Phrases",
    category: "vocab",
    language: "ja",
    description: "Phrases you'll reach for constantly in everyday conversation.",
    cards: [
      { targetText: "ありがとうございます", nativeText: "thank you", exampleSentence: "Reading: arigatou gozaimasu" },
      { targetText: "すみません", nativeText: "excuse me / I'm sorry", exampleSentence: "Reading: sumimasen — also used to get someone's attention." },
      { targetText: "お願いします", nativeText: "please", exampleSentence: "Reading: onegaishimasu" },
      { targetText: "はい", nativeText: "yes", exampleSentence: "Reading: hai" },
      { targetText: "いいえ", nativeText: "no", exampleSentence: "Reading: iie" },
      { targetText: "わかりました", nativeText: "understood / got it", exampleSentence: "Reading: wakarimashita" },
      { targetText: "わかりません", nativeText: "I don't understand", exampleSentence: "Reading: wakarimasen" },
      { targetText: "大丈夫です", nativeText: "it's okay / I'm fine", exampleSentence: "Reading: daijoubu desu" },
      { targetText: "頑張って", nativeText: "good luck / do your best", exampleSentence: "Reading: ganbatte" },
      { targetText: "お疲れ様です", nativeText: "thanks for your hard work", exampleSentence: "Reading: otsukaresama desu — said to colleagues at the end of the day." },
      { targetText: "いただきます", nativeText: "said before eating", exampleSentence: "Reading: itadakimasu — roughly \"I gratefully receive this meal.\"" },
      { targetText: "ごちそうさまでした", nativeText: "said after eating", exampleSentence: "Reading: gochisousama deshita — thanks for the meal." },
    ],
  },
];
